Repository gioblu/PJON, pull requests merged in 2018-06, with the labels that each got.

#213 Add TS strategy for LINUX and TS SWBB surrogate
  examples/ARDUINO/Local/ThroughSerial/BlinkWithResponse/Receiver/Receiver.ino
  examples/ARDUINO/Local/ThroughSerial/SoftwareBitBangSurrogate/Surrogate/Surrogate.ino
  examples/LINUX/Local/ThroughSerial/BlinkTest/Transmitter/Makefile
  examples/LINUX/Local/ThroughSerial/BlinkTest/Transmitter/Transmitter.cpp
  examples/LINUX/Local/ThroughSerial/BlinkWithAck/Transmitter/Makefile
  examples/LINUX/Local/ThroughSerial/BlinkWithAck/Transmitter/Transmitter.cpp
  examples/LINUX/Local/ThroughSerial/BlinkWithResponse/Transmitter/Makefile
  examples/LINUX/Local/ThroughSerial/BlinkWithResponse/Transmitter/Transmitter.cpp
  examples/LINUX/Local/ThroughSerial/RemoteWorker/Transmitter/Makefile
  examples/LINUX/Local/ThroughSerial/RemoteWorker/Transmitter/Transmitter.cpp
Labels: enhancement

#217 Add wait for txe pin status change
  src/strategies/ThroughSerial/ThroughSerial.h
Labels: bug

#208 add ESP32 support (#207)
  library.properties
  src/interfaces/ARDUINO/PJON_ARDUINO_Interface.h
  src/interfaces/ARDUINO/TCPHelper_ARDUINO.h
  src/interfaces/ARDUINO/UDPHelper_ARDUINO.h
  src/strategies/PJON_Strategies.h
Labels: enhancement, port

#219 Robustified startup of LUDP-SWBB switches
  examples/ARDUINO/Local/SoftwareBitBang/Tunneler/BlinkingRGBSwitch/BlinkingRGBSwitch.ino
  examples/ARDUINO/Local/SoftwareBitBang/Tunneler/SwitchA/SwitchA.ino
  examples/ARDUINO/Local/SoftwareBitBang/Tunneler/SwitchB/SwitchB.ino
Labels: enhancement
