Repository gioblu/PJON, pull requests merged in 2019-04, with the labels that each got.

#285 Fixed build problem in Arduino IDE greater than v1.8.6
  src/interfaces/ARDUINO/PJON_ARDUINO_Interface.h
  src/interfaces/ARDUINO/UDPHelper_ARDUINO.h
Labels: bug

#286 Fixed static so esp32 compiles on Arduino IDE 1.8.6+
  examples/ESP32/ESPNOW/PingPongArduinoIDE/Device1/Device1.ino
  examples/ESP32/ESPNOW/PingPongArduinoIDE/Device2/Device2.ino
Labels: bug

#287 Added max_tx_power to struct
  examples/ESP32/ESPNOW/PingPongArduinoIDE/Device1/Device1.ino
  examples/ESP32/ESPNOW/PingPongArduinoIDE/Device2/Device2.ino
Labels: bug

#290 Adds support for STM32-duino installed via the board.json
  library.properties
Labels: enhancement

#291 STM32 Workarround for missing ethernet refernces
  src/strategies/PJON_Strategies.h
Labels: BUG
